== Enable and Configure the GitLab Plugin

The GitLab plugin enables {product_rhdh_name} to integrate with GitLab for source code management and to automatically discover and import `catalog-info.yaml` files from GitLab repositories.

=== Update Dynamic Plugins Configuration

First, enable the GitLab plugins by updating your dynamic plugins ConfigMap:

. Navigate to *Workloads > ConfigMaps* and click on `{m2_rhdh_plugins_cm_name}`.
. Click *Edit ConfigMap*.
. Update the `dynamic-plugins.yaml` content to include GitLab plugins:
+
[source,yaml,subs=attributes+]
----
includes:
  - dynamic-plugins.default.yaml
plugins:
  - package: './dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic'
    disabled: false
  - package: './dynamic-plugins/dist/backstage-plugin-kubernetes'
    disabled: false
  - package: './dynamic-plugins/dist/janus-idp-backstage-plugin-keycloak-backend-dynamic'
    disabled: false
  - package: './dynamic-plugins/dist/backstage-plugin-catalog-backend-module-keycloak-dynamic'
    disabled: false
  - package: './dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-gitlab-dynamic'
    disabled: false
  - package: './dynamic-plugins/dist/backstage-plugin-catalog-backend-module-gitlab-dynamic'
    disabled: false
----
. Click *Save*.

=== Create GitLab Integration Secret

Create a Secret to store GitLab credentials:

. Navigate to *Workloads > Secrets* and click *Create > Key/value secret*.
. Set the secret name to `gitlab-secrets`.
. Add the following key-value pairs:
+
[cols="1,1"]
|===
|Key |Value

|`GITLAB_HOST`
|`gitlab-gitlab.{cluster_apps_domain}`

|`GITLAB_TOKEN`
|`\{gitlab_integration_token}`

|`GITLAB_CLIENT_ID`
|`\{gitlab_oauth_client_id}`

|`GITLAB_CLIENT_SECRET`
|`\{gitlab_oauth_client_secret}`
|===
. Click *Create*.

=== Update App Configuration for GitLab

Update your app-config ConfigMap to include GitLab integration:

. Navigate to *Workloads > ConfigMaps* and click on `{m2_rhdh_cm_name}`.
. Click *Edit ConfigMap*.
. Add the following GitLab configuration to your `app-config.yaml`:
+
[source,yaml,subs=attributes+]
----
catalog:
  providers:
    keycloakOrg:
      default:
        baseUrl: ${KEYCLOAK_BASE_URL}
        loginRealm: ${KEYCLOAK_LOGIN_REALM}
        realm: ${KEYCLOAK_REALM}
        clientId: $\{KEYCLOAK_CLIENT_ID}
        clientSecret: ${KEYCLOAK_CLIENT_SECRET}
        schedule:
          frequency:
            minutes: 30
          timeout:
            minutes: 3
          initialDelay:
            seconds: 15
    gitlab:
      yourProviderId:
        host: ${GITLAB_HOST}
        token: ${GITLAB_TOKEN}
        orgEnabled: true
        group: 'backstage-demo'
        schedule:
          frequency:
            minutes: 5
          timeout:
            minutes: 3

integrations:
  gitlab:
    - host: ${GITLAB_HOST}
      token: ${GITLAB_TOKEN}
      baseUrl: https://${GITLAB_HOST}

signInPage: oidc
auth:
  environment: production
  session:
    secret: ${BACKEND_SECRET}
  providers:
    oidc:
      production:
        metadataUrl: ${KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM}/.well-known/openid-configuration
        clientId: $\{KEYCLOAK_CLIENT_ID}
        clientSecret: ${KEYCLOAK_CLIENT_SECRET}
        prompt: auto
----
. Click *Save*.

=== Update Backstage CR with GitLab Secrets

Update your Backstage CR to include the GitLab secrets:

. Navigate to your Backstage CR and click the *YAML* tab.
. Update the `extraEnvs.secrets` section:
+
[source,yaml,subs=attributes+]
----
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
        - name: {m2_rhdh_cm_name}
    dynamicPluginsConfigMapName: {m2_rhdh_plugins_cm_name}
    extraEnvs:
      secrets:
        - name: {m2_keycloak_secret_name}
        - name: gitlab-secrets
    route:
      enabled: true
----
. Click *Save*.

=== Verify GitLab Integration

After the pods restart:

. Log in to your {product_rhdh_name} instance.
. You should continue to use Keycloak as the primary authentication method.
. Navigate to the *Catalog* to see imported components from GitLab repositories.
. The system will automatically discover and import `catalog-info.yaml` files from repositories in the configured GitLab group.
. Check the Backstage pod logs to verify successful synchronization with GitLab.

[NOTE]
====
The GitLab integration will scan the specified group (`backstage-demo` in this example) for repositories containing `catalog-info.yaml` files and automatically import them into the Backstage catalog. Ensure that the GitLab token has appropriate permissions to access the target repositories and groups.
====