:m2_rhdh_project: setup-rhdh
:m2_rhdh_instance: rhdh
:m2_rhdh_cm_name: rhdh-config
:m2_rhdh_plugins_cm_name: dynamic-plugins-rhdh

= Manage Plugins

== Plugin Architecture

{product_rhdh_name} includes a comprehensive set of pre-installed dynamic plugins that extend its functionality beyond the core Backstage capabilities. These plugins are based on the https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.6/html/dynamic_plugins_reference/con-preinstalled-dynamic-plugins[dynamic plugin architecture] and provide integrations with various tools and services commonly used in enterprise development environments.

Pre-installed dynamic plugins include integrations for:

* Authentication providers (Keycloak, GitHub, GitLab)
* Source control systems (GitHub, GitLab, Bitbucket)
* CI/CD platforms (Jenkins, Tekton, GitHub Actions)
* Container registries and Kubernetes
* Monitoring and observability tools
* Documentation platforms

While these plugins are pre-installed with {product_rhdh_name}, most must be explicitly enabled and configured to function properly. This design allows administrators to selectively activate only the integrations needed for their specific environment.

[NOTE]
====
Third-party plugins can also be integrated with {product_rhdh_name}, but they require proper packaging and configuration. For more information on working with third-party plugins, refer to the https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.6/html/installing_and_viewing_plugins_in_red_hat_developer_hub/assembly-third-party-plugins#proc-export-third-party-plugins-rhdh_assembly-third-party-plugins[official documentation].
====

== Create a Dynamic Plugins Configuration

Dynamic plugins in operator-based deployments of {product_rhdh_name} are configured using a dedicated ConfigMap. This ConfigMap defines which plugins should be enabled and their specific configuration parameters.

=== Understanding Plugin Configuration

The {product_rhdh_name} Operator reads plugin configurations from a ConfigMap that contains a `dynamic-plugins.yaml` file. This configuration file specifies:

* Which plugins to enable or disable
* Plugin-specific configuration parameters
* Dependencies and package information

For detailed information on configuring dynamic plugins with the operator, refer to the https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.6/html/installing_and_viewing_plugins_in_red_hat_developer_hub/rhdh-installing-rhdh-plugins_title-plugins-rhdh-about#proc-config-dynamic-plugins-rhdh-operator_rhdh-installing-rhdh-plugins[official plugin configuration guide].

=== Create the Dynamic Plugins ConfigMap

. Log in to the {openshift_console_url}[OpenShift Web Console].
. Ensure you're in the `{m2_rhdh_project}` project.
. Navigate to *Workloads > ConfigMaps*.
. Click the *Create ConfigMap* button.
. Switch to the YAML view and paste the following configuration:
+
[source,yaml,subs=attributes+]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: {m2_rhdh_plugins_cm_name}
  namespace: {m2_rhdh_project}
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: './dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic'
        disabled: false
      - package: './dynamic-plugins/dist/backstage-plugin-kubernetes'
        disabled: false
      - package: './dynamic-plugins/dist/janus-idp-backstage-plugin-keycloak-backend-dynamic'
        disabled: false
      - package: './dynamic-plugins/dist/backstage-plugin-catalog-backend-module-keycloak-dynamic'
        disabled: false
----
. Click *Create* to create the ConfigMap.

=== Update the Backstage Custom Resource

Now you need to update your Backstage CR to reference the dynamic plugins ConfigMap.

. Navigate to *Operators > Installed Operators* in the OpenShift Web Console.
. Click on *{product_rhdh_name}*.
. Select the *Backstage* tab, then click on your `{m2_rhdh_instance}` instance.
. Click the *YAML* tab to edit the resource.
. Update the `spec.application` section to include the dynamic plugins configuration:
+
[source,yaml,subs=attributes+]
----
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
        - name: {m2_rhdh_cm_name}
    # Add this line to your existing Backstage CR
    dynamicPluginsConfigMapName: {m2_rhdh_plugins_cm_name}
    route:
      enabled: true
----
. Click *Save* to apply the changes.

TODO: Add instructions to verify a new RHDH POD started

=== Verify Plugin Loading

After the Backstage pods restart, you can verify that plugins are loading correctly:

. Visit your {product_rhdh_name} instance URL.
. Navigate to `\https://{m2_rhdh_instance}-backstage-{m2_rhdh_project}.{cluster_apps_domain}/api/dynamic-plugins-info/loaded-plugins` to view the loaded plugins API endpoint.
. Alternatively, log in to {product_rhdh_name} as an administrator and visit *Administration > Plugins* to view enabled plugins through the UI.

== Enable and Configure the Keycloak Plugin

The Keycloak plugin enables {product_rhdh_name} to integrate with Keycloak for authentication and to import User and Group entities into the Backstage catalog.

=== Create Keycloak Integration Secret

First, create a Secret to store Keycloak connection details:

. In the OpenShift Web Console, navigate to *Workloads > Secrets*.
. Click *Create > Key/value secret*.
. Set the secret name to `keycloak-secrets`.
. Add the following key-value pairs:
+
[cols="1,1"]
|===
|Key |Value

|`KEYCLOAK_BASE_URL`
|`\https://keycloak-keycloak.{cluster_apps_domain}`

|`KEYCLOAK_LOGIN_REALM`
|`backstage`

|`KEYCLOAK_REALM`
|`backstage`

|`KEYCLOAK_CLIENT_ID`
|`backstage`

|`KEYCLOAK_CLIENT_SECRET`
|`\{keycloak_client_secret}`
|===
. Click *Create*.

=== Update App Configuration

Update your app-config ConfigMap to include Keycloak integration:

. Navigate to *Workloads > ConfigMaps* and click on `{m2_rhdh_cm_name}`.
. Click *Edit ConfigMap*.
. Replace the `app-config.yaml` content with:
+
[source,yaml,subs=attributes+]
----
app:
  title: Red Hat Developer Hub
  baseUrl: https://{m2_rhdh_instance}-backstage-{m2_rhdh_project}.{cluster_apps_domain}

auth:
  providers:
    keycloak:
      development:
        metadataUrl: ${KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM}
        clientId: ${KEYCLOAK_CLIENT_ID}
        clientSecret: ${KEYCLOAK_CLIENT_SECRET}
        scope: 'openid profile email groups'
    guest:
      dangerouslyAllowOutsideDevelopment: true

backend:
  baseUrl: https://{m2_rhdh_instance}-backstage-{m2_rhdh_project}.{cluster_apps_domain}
  cors:
    origin: https://{m2_rhdh_instance}-backstage-{m2_rhdh_project}.{cluster_apps_domain}

catalog:
  providers:
    keycloakOrg:
      default:
        baseUrl: ${KEYCLOAK_BASE_URL}
        loginRealm: ${KEYCLOAK_LOGIN_REALM}
        realm: ${KEYCLOAK_REALM}
        clientId: ${KEYCLOAK_CLIENT_ID}
        clientSecret: ${KEYCLOAK_CLIENT_SECRET}
        schedule:
          frequency:
            minutes: 30
          timeout:
            minutes: 3
          initialDelay:
            seconds: 15

integrations:
  keycloak:
    - host: keycloak-keycloak.{cluster_apps_domain}
      baseUrl: https://keycloak-keycloak.{cluster_apps_domain}
      realm: backstage
----
. Click *Save*.

=== Update Backstage CR with Secret References

Update your Backstage CR to reference the Keycloak secrets:

. Navigate to your Backstage CR and click the *YAML* tab.
. Update the `spec.application` section to include environment variables from the secret:
+
[source,yaml,subs=attributes+]
----
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
        - name: {m2_rhdh_cm_name}
    dynamicPluginsConfigMapName: {m2_rhdh_plugins_cm_name}
    extraEnvs:
      secrets:
        - name: keycloak-secrets
    route:
      enabled: true
----
. Click *Save*.

=== Verify Keycloak Integration

After the pods restart:

. Log in to your {product_rhdh_name} instance.
. You should now see a *Keycloak* option on the sign-in page alongside *Guest*.
. Navigate to the *Catalog* and look for imported User and Group entities from Keycloak.
. Check the Backstage pod logs to verify successful synchronization with Keycloak.

== Enable and Configure the GitLab Plugin

The GitLab plugin enables {product_rhdh_name} to integrate with GitLab for source code management and to automatically discover and import `catalog-info.yaml` files from GitLab repositories.

=== Update Dynamic Plugins Configuration

First, enable the GitLab plugins by updating your dynamic plugins ConfigMap:

. Navigate to *Workloads > ConfigMaps* and click on `{m2_rhdh_plugins_cm_name}`.
. Click *Edit ConfigMap*.
. Update the `dynamic-plugins.yaml` content to include GitLab plugins:
+
[source,yaml,subs=attributes+]
----
includes:
  - dynamic-plugins.default.yaml
plugins:
  - package: './dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic'
    disabled: false
  - package: './dynamic-plugins/dist/backstage-plugin-kubernetes'
    disabled: false
  - package: './dynamic-plugins/dist/janus-idp-backstage-plugin-keycloak-backend-dynamic'
    disabled: false
  - package: './dynamic-plugins/dist/backstage-plugin-catalog-backend-module-keycloak-dynamic'
    disabled: false
  - package: './dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-gitlab-dynamic'
    disabled: false
  - package: './dynamic-plugins/dist/backstage-plugin-catalog-backend-module-gitlab-dynamic'
    disabled: false
----
. Click *Save*.

=== Create GitLab Integration Secret

Create a Secret to store GitLab credentials:

. Navigate to *Workloads > Secrets* and click *Create > Key/value secret*.
. Set the secret name to `gitlab-secrets`.
. Add the following key-value pairs:
+
[cols="1,1"]
|===
|Key |Value

|`GITLAB_HOST`
|`gitlab-gitlab.{cluster_apps_domain}`

|`GITLAB_TOKEN`
|`\{gitlab_integration_token}`

|`GITLAB_CLIENT_ID`
|`\{gitlab_oauth_client_id}`

|`GITLAB_CLIENT_SECRET`
|`\{gitlab_oauth_client_secret}`
|===
. Click *Create*.

=== Update App Configuration for GitLab

Update your app-config ConfigMap to include GitLab integration:

. Navigate to *Workloads > ConfigMaps* and click on `{m2_rhdh_cm_name}`.
. Click *Edit ConfigMap*.
. Add the following GitLab configuration to your `app-config.yaml`:
+
[source,yaml,subs=attributes+]
----
catalog:
  providers:
    keycloakOrg:
      default:
        baseUrl: ${KEYCLOAK_BASE_URL}
        loginRealm: ${KEYCLOAK_LOGIN_REALM}
        realm: ${KEYCLOAK_REALM}
        clientId: ${KEYCLOAK_CLIENT_ID}
        clientSecret: ${KEYCLOAK_CLIENT_SECRET}
        schedule:
          frequency:
            minutes: 30
          timeout:
            minutes: 3
          initialDelay:
            seconds: 15
    gitlab:
      yourProviderId:
        host: ${GITLAB_HOST}
        token: ${GITLAB_TOKEN}
        orgEnabled: true
        group: 'backstage-demo'
        schedule:
          frequency:
            minutes: 30
          timeout:
            minutes: 3

integrations:
  keycloak:
    - host: keycloak-keycloak.{cluster_apps_domain}
      baseUrl: https://keycloak-keycloak.{cluster_apps_domain}
      realm: backstage
  gitlab:
    - host: ${GITLAB_HOST}
      token: ${GITLAB_TOKEN}
      baseUrl: https://${GITLAB_HOST}

auth:
  providers:
    keycloak:
      development:
        metadataUrl: ${KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM}
        clientId: ${KEYCLOAK_CLIENT_ID}
        clientSecret: ${KEYCLOAK_CLIENT_SECRET}
        scope: 'openid profile email groups'
    gitlab:
      development:
        clientId: ${GITLAB_CLIENT_ID}
        clientSecret: ${GITLAB_CLIENT_SECRET}
        audience: https://${GITLAB_HOST}
        scope: 'read_user read_repository write_repository'
    guest:
      dangerouslyAllowOutsideDevelopment: true
----
. Click *Save*.

=== Update Backstage CR with GitLab Secrets

Update your Backstage CR to include the GitLab secrets:

. Navigate to your Backstage CR and click the *YAML* tab.
. Update the `extraEnvs.secrets` section:
+
[source,yaml,subs=attributes+]
----
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
        - name: {m2_rhdh_cm_name}
    dynamicPluginsConfigMapName: {m2_rhdh_plugins_cm_name}
    extraEnvs:
      secrets:
        - name: keycloak-secrets
        - name: gitlab-secrets
    route:
      enabled: true
----
. Click *Save*.

=== Verify GitLab Integration

After the pods restart:

. Log in to your {product_rhdh_name} instance.
. You should now see *GitLab* as an authentication option.
. Navigate to the *Catalog* to see imported components from GitLab repositories.
. The system will automatically discover and import `catalog-info.yaml` files from repositories in the configured GitLab group.
. Check the Backstage pod logs to verify successful synchronization with GitLab.

[NOTE]
====
The GitLab integration will scan the specified group (`backstage-demo` in this example) for repositories containing `catalog-info.yaml` files and automatically import them into the Backstage catalog. Ensure that the GitLab token has appropriate permissions to access the target repositories and groups.
====