:imagesdir: ../../assets/images

= The Sigstore Admission Controller 

As outlined in this chapter's introduction, admission controllers are our "last line of defense", should someone try to deploy directly to the cluster (assuming that all "regular" deployments are coming from a security-augmented supply chain, using ADS products and configurations).

== How does it work?

The Red Hat build of the Sigstore Admission Controller (part of Red Hat Trusted Artifact Signer) can be installed via an operator.

Following the installation, it relies on three k8s CRs (Custom Resources):

=== The PolicyController Resource

The PolicyController CR defines the global behaviour of the Admission Controller:

* Which namespaces it should act on
** typically as an "opt-in" based on namespace labels
** "opt-out" is also possible, but it should be noted that this might cause problems with system namespaces, if not used cautiously. When applying "opt-out" patterns, a `no-match-policy` with "warn" should be defined (more on that in the exercise).

* Additional global configuration, such as custom certificate authorities (CA) or the aforementioned `no-match-policy` that defines the default behaviour (which can be overruled by the `ClusterImagePolicy`)


=== The TrustRoot Resource

If you went through previous RHTAS chapters and exercises, the name "Trust Root" should ring a bell.
The Trust Root is the collection and configuration of public certificates of the various services that Trusted Artifact Signer provides, such as Fulcio (the Certificate Issuer) and Rekor (the Transparency Database).

When you issue a `cosign initialize`, a Trust Root is obtained from the TUF (The Update Framework) endpoint of the TAS installation and stored in the user's home directory `~/.sigstore`. `cosign` reads that endpoint from the `COSIGN_MIRROR` / `COSIGN_ROOT` variables the terminal already has set, and from `cosign` 3.x on it prints nothing at all on success - so to see what it recorded, read the file it wrote:

[source,console]
----
podman-terminal:/workspace/l3-enablement-helpers$ cosign initialize
WARNING: Fetching initial root from URL without providing its checksum is deprecated and will be disallowed in a future Cosign release. Please provide the initial root checksum via the --root-checksum argument.
podman-terminal:/workspace/l3-enablement-helpers$ cat ~/.sigstore/root/remote.json
{"mirror":"https://tuf-tssc-tas.apps.cluster-vtm4r.dynamic.redhatworkshops.io"}
podman-terminal:/workspace/l3-enablement-helpers$ ls ~/.sigstore/root/
remote.json
tuf-tssc-tas.apps.cluster-vtm4r.dynamic.redhatworkshops.io
tuf-tssc-tas.apps.cluster-vtm4r.dynamic.redhatworkshops.io.json
----

The `mirror` above is the TUF endpoint, and the directory beside it - named after that same endpoint - holds the trust root itself.

The same applies here, but we need to create it as a k8s CR.

[IMPORTANT]
====
Same as with `cosign initialize`, we can also manually define our custom Trust Root by manually defining the certificates and where they are stored, *BUT* 

Only by using TUF (what we see as `mirror` in the above example) the controller will take care of refreshing the certificates after they have been rotated in the central RHTAS instance. +
If we use a manually configured Trust Root, we have to manually update the certificates - while the policy-controller will do that automatically using TUF.
====

=== The ClusterImagePolicy

The ClusterImagePolicy defines (for the namespaces that have been configured to be watched via the `PolicyController` Resource) 

* The images that it should be applied
* The "Authorities" that the image signatures will be verified against
* Attestations that should be validated
* `cue` or `Rego` policies that should be validated against images, image metadata and/or attestations
* Behaviour for failed validations 
** if none is defined at the policy level, the default behaviour (see above) at the `PolicyController` level is used
** Can be `enforce` (image will be rejected) or `warn` (image accepted but warning issued)

Given the flexibility and abundance of options, we will have to prepare our exercises (next chapter).

We will need 

* an unsigned image
* a keylessly signed image
* an image signed with a cosign key (similar to what our default Tekton Chains configuration does)
* a signed image with a (signed) attestation

But, fear not - we have prepared a number of scripts for you that will do the majority of the preparation for you. 

[NOTE] 
====
All of the scripts and artifacts prepared for you should not only make the lab experience a (hopefully) smooth one, but are there for you to re-use, study and dissect - so please feel free to take a deeper look.
====